Zebra-CMS/Zebra/Controllers/CPanelController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Configuration;
using System.Reflection;
using System.Web;
using System.Web.Mvc;
using Zebra.CustomAttributes;
using Zebra.DataRepository.Models;
using Zebra.Globalization;
using Zebra.ViewModel;
using Zebra.Services.Interfaces;
using Zebra.Services.Operations;
using System.Text;

namespace Zebra.Controllers
{
    public class CPanelController : ZebraController
    {
        public CPanelController(NodeOperations nodeOperations, FieldOperations fieldOperations, UserOperations userOperations) : base(nodeOperations, fieldOperations, userOperations, true)
        {
             
        }

        // GET: CPanel
        public override ActionResult Index()
        {
            //NameValueCollection section = (NameValueCollection)ConfigurationManager.GetSection("ZebraUtility");
            //string userName = section["userName"];
            //string userPassword = section["userPassword"];
            return RedirectToAction("Editor");
        }

        // GET: CPanel/Editor
        [ZebraAuthorize(Roles ="Editor")]
        public ActionResult Editor()
        {
            Node root = _nodeop.GetRootNode();
            root = _userOperations.FilterByUser(CurrentUser, root);
           // ((NodeOperations)_nodeop).CreateContentMap();
            var list = new List<Node>();
            list.Add(root);
            ViewBag.Root = list;
            ViewBag.Utilities = new List<string>
            {   "Zebra.Utilities.UtilityProcessor.FieldBuilderUtility, Zebra",
                "Zebra.Utilities.UtilityProcessor.InheritanceUtility, Zebra",
                "Zebra.Utilities.UtilityProcessor.RoadmapUtility, Zebra",
                "Zebra.Utilities.UtilityProcessor.ValidationUtility, Zebra"
            };
            return View();
        }

        //Default nodeid is Template node Id
        [ZebraAuthorize(Roles = "Editor")]
        public ActionResult NodeTree(string nodeid= "8087FA7D-6753-40B9-9F3A-7AE62E882258")
        {
            var list = new List<Node>();
            var node = _nodeop.GetNode(nodeid);
            node = _userOperations.FilterByUser(CurrentUser, node);
            list.Add(node);
            if(list.Count == 0)
            {
                return null;
            }
            return View(list);
        }

        [ZebraAuthorize(Roles = "Editor")]
        public ActionResult NodeSearchResult(string nameorid)
        {
            return View(_userOperations.FilterByUser(CurrentUser, _nodeop.SearchNode(nameorid)));
        }

        [ZebraAuthorize(Roles = "Editor")]
        public ActionResult NodeBrowser(string nodeid, string languageid = "B45089D2-CF01-4351-B6A6-40FBFFD64DC3")
        {
            var node = _nodeop.GetNode(nodeid);
            node = _userOperations.FilterByUser(CurrentUser, node);
            if(node == null)
            {
                return null;
            }
            var language = LanguageManager.GetLanguageById(languageid);
            var languages = LanguageManager.GetAllLanguages();
            var list = _fieldOperations.GetInclusiveFieldsOfTemplate(node.Id.ToString());
            List<string> htmllist = new List<string>();
            IEnumerable<NodeFieldMap> nodefieldmap = ((IStructureOperations)_nodeop).GetNodeFieldMapData(node.Id.ToString(), language.Id.ToString());
            //   foreach (var field in list)
            foreach(var nodefield in nodefieldmap)
            {
                //         htmllist.Add(_fieldOperations.GetRenderedField(field.Id.ToString()));
                htmllist.Add(_fieldOperations.GetRenderedField(nodeid, nodefield.FieldId.ToString(), nodefield.Id.ToString()));
            }
            var orderedfields = new Dictionary<string, List<string>>();

            foreach (var nodefield in nodefieldmap)
            {
                if (nodefield.Field != null)
                {
                    var templatename = nodefield.Field.GetTemplate().TemplateName;
                    if (orderedfields.ContainsKey(templatename))
                    {
                        orderedfields[templatename].Add(_fieldOperations.GetRenderedField(nodeid, nodefield.FieldId.ToString(), nodefield.Id.ToString()));
                    }
                    else
                    {
                        var tmplist = new List<string>() { _fieldOperations.GetRenderedField(nodeid, nodefield.FieldId.ToString(), nodefield.Id.ToString()) };
                        orderedfields.Add(templatename, tmplist);
                    }
                }
            }

            var presentlanguages = ((IStructureOperations)_nodeop).GetNodeLanguages(node.Id.ToString());
            return View(model: new NodeBrowserModel() { fields = htmllist, orderedfields = orderedfields,  node = node, template = node.Template, currentlanguage = language, alllanguages = languages, allnodelanguages = presentlanguages });
        }

        [ZebraAuthorize(Roles = "Editor")]
        public ActionResult RenderUtility(string fullyqualifiedname, string method = "RenderView", dynamic data = null)
        {
            var type = Type.GetType(fullyqualifiedname);
            Assembly assembly = null;
            if (type != null && (assembly = Assembly.GetAssembly(type)) != null)
            {
                var instance = Activator.CreateInstance(type, null);
                object[] args = new[] { data };
                var mi = type.GetMethod("HasExecutionRights");
                data = mi.Invoke(instance, args);
                if (data.Equals(true))
                {
                    mi = type.GetMethod(method);
                    var path = mi.Invoke(instance, args).ToString();
                    if (VirtualPathUtility.IsAppRelative(path))
                    {
                        return PartialView(viewName: path, model: args[0]);
                    }
                }
            }
            return PartialView();
        }
        
        [HttpGet]
        public ActionResult PageDesigner(string nodeid)
        {
            if(!string.IsNullOrWhiteSpace(nodeid))
            {
                var node = _nodeop.GetNode(nodeid);
                if(node != null)
                {
                    var designdetailfieldid = "06C00328-A252-4BA9-A8C2-95A354A90E2F";
                    var data = _nodeop.GetValueForField(node.Id.ToString(), designdetailfieldid);
                    var parents = _nodeop.GetAllParentNodes(nodeid);
                    StringBuilder sb = new StringBuilder();
                    parents.Pop();
                    while (parents.Count > 0)
                    {
                        var parent = parents.Pop();
                        sb.Append('/').Append(parent.NodeName);
                    }
                    ViewBag.NodeId = nodeid;
                    ViewBag.NodePath = sb.ToString();
                    ViewBag.DesignerDetailFieldId = designdetailfieldid;
                    ViewBag.DefaultLanguageId = LanguageManager.GetDefaultLanguage().Id.ToString();
                    return View(model: HttpUtility.HtmlDecode(data));
                }
            }
            return null;
        }
    }
}

Zebra-CMS/Zebra/Views/CPanel/NodeBrowser.cshtml
@using Zebra.ZebraHelpers
@using Zebra.ViewModel
@using Newtonsoft.Json
@{
    Layout = null;
    var nodeop = Zebra.Services.Operations.OperationsFactory.NodeOperations;
} 
@model NodeBrowserModel

<div class="zebra-node-details">
    <p>Name : @Model.node.NodeName</p>
    <p>Node ID: @Model.node.Id</p>

    <p>Template Name: @Model.template.TemplateName</p>
    <p>Template ID: @Model.template.Id</p>
    @{ var nodepath = nodeop.GetAllParentNodes(Model.node.Id.ToString());
    }
    <p>Node Path: @Html.LoadNodePath(nodepath)</p>
</div>
<div>
    @foreach (var t in Zebra.Framework.Executors.FrameworkExecutor.GetFrameworkDataList(@Model.node.Id))
    {
        switch (@t.ProcessName.ToLowerInvariant())
        {
            case "roadmap":
                <p>@t.ProcessName : @nodeop.GetNode(t.RelatedId.ToString()).NodeName => Phase : @nodeop.GetNode((string)((dynamic)JsonConvert.DeserializeObject(@t.ProcessData))["currentphaseid"]).NodeName</p>
                break;
            case "validation":
                <p>@t.ProcessName : @nodeop.GetNode(t.RelatedId.ToString()).NodeName => Status : @(((dynamic)JsonConvert.DeserializeObject(@t.ProcessData))["validation"].Value)</p>
            break;
            default:
                <text>@t.ProcessName : @t.ProcessData</text>
                break;
        }
    }


</div>
<button class="zebra-save-data">Save</button>
<select data-nodeid="@Model.node.Id" class="zebra-language-selector">
    @foreach (var lang in Model.alllanguages)
    {
        <option @(Model.currentlanguage.Id==lang.Id ? "selected" : "") value="@lang.Id">@lang.CultureName</option>
    }
</select>
<a class="page-designer-link" href="./PageDesigner?nodeid=@Model.node.Id" target="_blank">Page Designer</a>
<div class="zebra-field">
    <form class="zebra-field-data-form" enctype="multipart/form-data">
        <input type="hidden" name="nodeid" id="nodeid" value="@Model.node.Id" />
        <input type="hidden" name="nodelanguageid" id="nodelanguageid" value="@Model.currentlanguage.Id" />
       @if(Model.allnodelanguages.Count(x=>x.Id == Model.currentlanguage.Id) == 0)
        {
            <input type="button" class="zebra-add-locale" value="Add Locale"/>
       }
       else
       {
            <ul>
                @for (int i = 0; i < Model.orderedfields.Count; i++)
                {
                  
                        var keyvaluepair = Model.orderedfields.ElementAt(i);
                  
                    <li>
                        <span data-section-expanded="true" class="zebra-field-section-heading"><i class="fa fa-minus-square-o"></i><b>From: @keyvaluepair.Key</b></span>
                        <div class="zebra-field-section">
                            @Html.LoadFields(keyvaluepair.Value)
                        </div>
                    </li>
                }
            </ul>
        }
</form>
</div>

<script>
   
</script>


 
<style>
    .zebra-node-details
    {
        border-style: groove;
        min-height: 100px;
    }
    .zebra-field{
        max-height: calc(100vh - 310px);
    }
    .field {
            margin-left:3px;
            margin-right:3px;
            margin-top:1px;
            margin-bottom:3px;
            display: block;
        }
      .page-designer-link{
            float: right;
            margin: 10px;
            border: dotted;
      }
</style>

Zebra-CMS/Zebra/Views/CPanel/NodeSearchResult.cshtml
@using Zebra.DataRepository.Models
@model List<Node>
@{
    Layout = null;
}
<div>
    @foreach (var node in Model)
            {
        <div class="content-node" data-nodeid="@node.Id" node-expanded="false">
            <span class="node-icon-container"><i class="fa fa-circle-thin"></i></span>
            <p>@node.NodeName</p>
        </div>

    }
</div>

Zebra-CMS/Zebra/Views/CPanel/NodeTree.cshtml
@using Zebra.DataRepository.Models
@model List<Zebra.DataRepository.Models.Node>

@{
    Layout = null;
} 

    <div class="content-tree">
        <div class="content-tree-search">
            <input class="content-tree-search-text" type="text" placeholder="Search node..."/><i class="content-node-search-btn fa fa-search" onclick="javascript:SearchNode(this)"></i>
        </div>
        <div class="content-tree-search-result">
        </div>
        <div class="content-tree-nodes">
            @foreach (var node in Model)
            {
                <div class="content-node" data-nodeid="@node.Id" node-expanded="false">
                    <span class="node-icon-container"><i class="fa fa-plus-square-o"></i></span>
                    <p>@node.NodeName</p>
                </div>

            }
        </div>
    </div>

<script>
    function SearchNode(e) {
        var txt = $(e.parentElement).find('.content-tree-search-text').val();
        if (txt !== null && txt.length > 0) {
            $.get("./NodeSearchResult?nameorid=" + txt, function (data) {
                $(".content-tree-search-result").show();
                $(".content-tree-search-result").html(data);
                $(".content-tree-nodes").hide();
            });
        }
        else {
            $(".content-tree-search-result").hide();
            $(".content-tree-nodes").show();
        }
    }

</script>



<style>
    .context-menu {
        border: 1px solid black;
        z-index: 1000;
        position: absolute;
        background-color: #feffff;
    }

    .content-tree-search {
        display: flex;
    }

    .node-icon-container{
        float: left;
        font-size: 12px;
        padding: 3px;
    }

    .content-tree-search-text {
        width: 100%;
        padding: 3px;
    }

    .content-node-search-btn {
        position: absolute;
        padding: 3px;
        right: 1px;
        background-color: white;
        align-self: center;
    }

        .context-menu ul {
            list-style: none;
            margin: 0 auto;
            padding-left: 1px;
            padding-right: 1px;
        }

        .context-menu li:hover {
            background: #ced9ea;
        }


    .content-tree {
        display: table-cell;
        width:300px;
        border-style: groove;
    }

    .content-tree-nodes{
        min-height: calc(100vh - 190px);
        max-height: calc(100vh - 190px);
        overflow-x: auto; 
    }
   
    .content-tree-search-result{
        display: none;
        min-height: calc(100vh - 190px);
        max-height: calc(100vh - 190px);
        overflow-x: auto;
    }

    body{
        margin: 0px;
        overflow: hidden;
    }

    header, footer{
        height:25px;
        width:100%;
        background-color: black;
    }
   
    .editor-container{
        display:block;
        height:100%;
    }

    .zebra-container{
        height:100%;
        margin:8px;
    }

    .item-container {
        display: table-cell;
         /*width:50%;*/
        border: groove;
        overflow-y: auto;
    }

    .tree-container{
        display:table;
        width:100%;
        /*min-height:600px;*/
        overflow-y: auto;
    }

    .model-dialog{
        border-style: solid;
    }

     .menu {
        border-style: groove;
        height: 100px;
    }

    .black-overlay {
        top: 0;
        position: fixed;
        width: 100%;
        height: 100%;
        z-index:10;
        background-color: rgba(1, 0, 0, 0.4);
        text-align:center;
    }

    .model-tree-popup {
        border-style: solid;
        background: white;
        position: fixed;
        top: 50%;
        left:50%;
        margin-left:-350px;
        margin-top:-200px;
        width: 700px;
        height: 400px;
        z-index:100;
    }

    .model-popup-buttons{
        position: absolute;
        bottom: 0;
        margin: 25px;
        right: 0;
        z-index: 10;
    }

</style>

<script>
    //$(document).on('click', '.close-button', function (e) {
    //    $(".zebra-fieldbuilder-container").remove();
    //    $('.black-overlay').remove();
    //});

    //$(document).on('click', '.remove-field-button', function (e) {
    //    var fielddiv = $(e.target).parent();
    //    $(fielddiv).remove();
    //});

    //$(document).on('click', '.save-field-button', function (e) {
    //    debugger;
    //    var typesarr = $('.fields-fieldbuilder .field select');
    //    var namesarr = $('.fields-fieldbuilder .field .fieldname input');
    //    var propertyarr = $('.fields-fieldbuilder .field .fieldproperty input');
    //    formdata = [];
    //    fieldsdata = [];
    //    template = {}
    //    template["templatenodeid"] = $(ZebraEditor_currentnode.element.parentElement).attr("data-nodeid");
    //    fieldsdata.push(template);
    //    for (i = 0; i < namesarr.length; i++) {
    //        field = {}
    //        field["name"] = namesarr[i].value;
    //        field["id"] = namesarr[i].id;
    //        field["typeid"] = typesarr[i].value;
    //        field["isstatic"] = propertyarr[i].value;
    //        fieldsdata.push(field);
    //    }
    //    fullyqualifiedname = {};
    //    fullyqualifiedname["fullyqualifiedname"] = "Zebra.Utilities.UtilityProcessor.FieldBuilderUtility,Zebra";
    //    methodname = {};
    //    methodname["methodname"] = "Process";
    //    formdata.push(fullyqualifiedname);
    //    formdata.push(methodname);
    //    formdata.push(fieldsdata);


    //    console.log(formdata);

    //    $.ajax({
    //        type: "POST",
    //        url: "/zebraapi/UtilityService/InvokeMethod",
    //        data: { '': JSON.stringify(formdata) },
    //        dataType: "json",
    //        async: true,
    //        success: function (json) {
    //            alert("Field Created ");
    //            console.log(json);
    //        },
    //        error: function (e) {
    //            console.log(e);
    //        }
    //    });
    //    $(".zebra-fieldbuilder-container").remove();
    //    $('.black-overlay').remove();
    //    if (ZebraEditor_currentnode.element != null) {
    //        LoadNodeBrowser($(ZebraEditor_currentnode.element.parentElement).attr('data-nodeid'), 'test', 'test', 'test');
    //    }
    //});

    //$(document).on('click', '.add-field-button', function (e) {
    //    $('.fields-fieldbuilder').append($('.field-sample').clone().attr('class', 'field'));
    //});
    //$(document).on('mouseup', function (e) {
    //    var fields = $('.zebra-fieldbuilder .field');

    //    for (var i = 0; i < fields.length; i++) {
    //        if ($(fields[i]).find('input').val() == '' && $(event.target.parentElement).attr('class') != 'field') {
    //            $(fields[i]).remove();
    //        }
    //    }
    //});

</script>

Zebra-CMS/Zebra/Views/CPanel/PageDesigner.cshtml
@{
    ViewBag.Title = "PageDesigner";
    Layout = "~/Views/Shared/EditorLayout.cshtml";
}
@model string
@{ 
    var data = Model;
    var nodepath = ViewBag.NodePath;
}
<div id="outer-container" class="outer-container">
    <input type="button" class="designer-add-container" value="Add Container"/>
    <input type="button" class="designer-add-action" value="Add Action" />
    <input type="button" class="designer-save-design" value="Save Design" />

</div>


<div class="outer-container-sample">
    <input type="button" class="designer-add-container" value="Add Container" />
    <input type="button" class="designer-add-action" value="Add Action" />
    <input type="button" class="designer-remove-container" value="Remove Container" />
    <input type="text" class="designer-container-class-name" placeholder="Container Class Name" />
</div>

<div class="datasource-container-sample">
    <span data-datasourceid=''><label>Datasource: </label><text><input type='button' class='designer-attach-datasource' value='Attach Datasource'></text></span>
</div>

<script>
    var nodepath = "@nodepath";
    var designerdata = JSON.parse("@data".replace(/&quot;/g, '\"'));
    console.log(JSON.stringify(designerdata));
    var parentcontainer = $('#outer-container');
    for (var i = 0; i < designerdata.length; i++) {
        if (designerdata[i]["iscontainer"]) {
            var childcontainer = AddContainer(parentcontainer, designerdata[i]["containerclass"]);
            var childdata = designerdata[i].children;
            TraverseChildren(childcontainer, childdata);
        }
        else
        {
            var id = designerdata[i]['actionid'];
            var name = designerdata[i]['actionname'];
            var datasourceid = designerdata[i]['datasourceid'];
            var datasourcename = designerdata[i]['datasourcename'];
            AddActionContainer(parentcontainer, id, name, datasourceid, datasourcename);
        }
    }

    function AddContainer(parent, classname) {
        var newcontainer = $('.outer-container-sample').clone();
        newcontainer.attr('class', 'outer-container');
        if (classname != undefined)
        {
            $(newcontainer).children('input.designer-container-class-name')[0].value = classname;
        }
        $(newcontainer).appendTo(parent);
        var depth = $(newcontainer).parents('.outer-container').length;
        $(newcontainer).prepend('<p>Depth: ' + depth + '</p>');
        return $(newcontainer);
    }

    function TraverseChildren(currentcontainer, currentdata) {
        for (var i = 0; i < currentdata.length; i++) {
            if (currentdata[i]["iscontainer"]) {
                var childcontainer = AddContainer(currentcontainer, currentdata[i]["containerclass"]);
                var childdata = currentdata[i].children;
                TraverseChildren(childcontainer, childdata);
            }
            else {
                var id = currentdata[i]['actionid'];
                var name = currentdata[i]['actionname'];
                var datasourceid = currentdata[i]['datasourceid'];
                var datasourcename = currentdata[i]['datasourcename'];
                AddActionContainer(currentcontainer, id, name, datasourceid, datasourcename);
            }
        }
    }


    $(document).on('click', '.designer-add-container', function () {
        var parent = this.parentElement;
        AddContainer(parent);
    });



    $(document).on('click', '.designer-add-action', function () {
        var parent = this.parentElement;
        ShowModelTreePopup('40feaa0d-4c88-4517-8297-5e21c5b06e21', '', '', '', function () { AddAction(parent, $(GetSelectedNodeInPopup())) });
    });

    function AddAction(parentcontainer, node)
    {
        var nodename = $(node).find('p')[0].innerHTML;
        var nodeid = node.attr('data-nodeid');
        AddActionContainer(parentcontainer, nodeid, nodename);
    }

    function AddActionContainer(parentcontainer, nodeid, nodename, datasourceid, datasourcename)
    {
        var action = "<div class='designer-action-container' data-nodeid='" + nodeid + "'><span><p>" + nodename + "<i class='fa fa-window-close-o action-remove'></i></p></span></div>";
        var $action = $(action);
        //$(action).appendTo(parentcontainer);
        AddDatasourceContainer($action, datasourceid, datasourcename);
        $(parentcontainer).append($action);
    }

    function AddDatasourceContainer(actioncontainer, datasourceid, datasourcename)
    {
        var datasourcecontainer = "";
        if (datasourceid != undefined && datasourceid != '') {
            datasourcecontainer = "<span data-datasourceid=" + datasourceid + "><label>Datasource: </label><text>" + datasourcename + "</text><i class='fa fa-window-close-o datasource-remove'></i></span>";
        }
        else {
            datasourcecontainer = $('.datasource-container-sample span').clone();
        }
        $(actioncontainer).append(datasourcecontainer);
    }

    //remove action
    $(document).on('click', '.designer-action-container i.action-remove', function () {
        $(this.parentElement.parentElement.parentElement).remove();
    });

    //remove datasource
    $(document).on('click', '.designer-action-container i.datasource-remove', function () {
        var actioncontainer = this.parentElement.parentElement;
        $(this.parentElement).remove();
        AddDatasourceContainer(actioncontainer);
    });

    $(document).on('click', '.designer-remove-container', function () {
        $(this.parentElement).remove();
    });

    $(document).on('click', '.designer-attach-datasource', function () {
        var btn = this;
        var para = btn.parentElement;
        var span = para.parentElement;
        var action = span.parentElement;
        ShowModelTreePopup('', '', '', '', function () {
            var node = $(GetSelectedNodeInPopup());
            var nodename = $(node).find('p')[0].innerHTML;
            var nodeid = node.attr('data-nodeid');
            $(span).remove();
            //  $(para).append(nodename);
            AddDatasourceContainer(action, nodeid, nodename);
            //$(span).attr('data-datasourceid', nodeid);
        });
    });

    $(document).on('click', '.designer-save-design', function () {
        var outercontainer = this.parentElement;
        var childdiv = $(outercontainer).children('div');
        var data = [];
        data = GetAllChildren(outercontainer);
        console.log(JSON.stringify(data));

        var formdata = {};
        formdata['nodeid'] = '@ViewBag.NodeId';
        formdata['@ViewBag.DesignerDetailFieldId'] = JSON.stringify(data);
        formdata['nodelanguageid'] = '@ViewBag.DefaultLanguageId';
        var ajaxRequest = $.ajax({
            type: "POST",
            url: "/zebraapi/nodeservice/savenode",
            data: formdata,
            success(data) {
                formdata = {};
                formdata['key'] = nodepath;
                var ajaxRequest = $.ajax({
                    type: "POST",
                    url: "/zebraapi/cacheservice/remove",
                    data: formdata,
                    success(data) {
                        alert('Saved');
                    }
                });
            }
        });
        ajaxRequest.done(function (data, textStatus, jqXHR) {

        });
        event.preventDefault();
    });

    function GetAllChildren(container)
    {
        var child = $(container).children('div');
        var data = [];
        for(var i = 0; i < child.length; i++)
        {
            var id = $(child[i]).attr('data-nodeid');
            var tmp = {};
            if (id == undefined) {
                var classname = $(child[i]).children('input.designer-container-class-name')[0].value;
                tmp['iscontainer'] = true;
                if (classname != undefined || classname != '')
                    tmp['containerclass'] = classname;
            }
            else {
                var actionspan = $(child[i]).children()[0];
                var actionname = $(actionspan).children()[0].innerText;
                var datasourcespan = $(child[i]).children()[1];
                var datasourceid = $(datasourcespan).attr('data-datasourceid');
                var datasourcename = undefined;
                if (datasourceid != undefined && datasourceid != '') {
                    datasourcename = $(datasourcespan).children('text')[0].innerText;
                }
                tmp['iscontainer'] = false;
                tmp['actionid'] = id;
                tmp['actionname'] = actionname;
                tmp['datasourceid'] = datasourceid;
                tmp['datasourcename'] = datasourcename;
            }
            tmp['children'] = GetAllChildren(child[i]);
            data.push(tmp);
        }
        return data;
    }

</script>

<style>
    .outer-container-sample{
        display: none;
    }

    .outer-container{
        display: block;
        border: ridge;
        padding: 10px;
    }

    .designer-action-container{
        margin: 5px;
        border: groove;
    }

    .datasource-container-sample{
        display: none;
    }

</style>

Zebra-CMS/Zebra/Views/CPanel/Utilities.cshtml
@{
    Layout = null;
}
@model List<string>
<div class="zebra-utilities">
    <div><input type="button" class="add-utilities" value="Add" /></div>
    @foreach (var utility in Model)
    {
        <div>
            @Html.Action("RenderUtility", "CPanel", new { fullyqualifiedname = utility })
        </div>
    }
    
</div>

<div class="zebra-utilities-popup">
    Full Qualified Method Name<input type="text" />
    <input type="button" value="Add" />
</div>

<script>
    $(".zebra-utilities input.add-utilities").on("click", function () {
        $('body').append("<div class='black-overlay'></div>");
        $(".zebra-utilities-popup").css("display", "block");
    });

</script>
<style>
    .zebra-utilities-popup{
        position:fixed;
        width:400px;
        padding:100px;
        margin: 0 auto;
        display: none;
        z-index:100;
        left:0;
        right:0;
        background-color:white;
    }

</style>